spring.application.name=quickstock-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/quick-stock
spring.datasource.username=postgres
spring.datasource.password=1546
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT (si lo usas)
# jwt.secret=mi-clave-secreta
# jwt.expiration=86400000 # 24 horas

# SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html